import { NextResponse } from 'next/server';
import { fetchWithRetry } from '@/lib/fetch-retry';

export async function POST(req: Request) {
  try {
    const { script, complianceReport, apiKey: clientApiKey } = await req.json();
    const apiKey = clientApiKey || process.env.GEMINI_API_KEY;

    if (!apiKey) {
      return NextResponse.json({ error: 'Missing Gemini API Key for Risk Mitigation Agent' }, { status: 400 });
    }

    const scriptText = script.map((line: { characterId: string, text: string }, idx: number) => 
      `[Scene ${idx + 1}] ${line.characterId.toUpperCase()}: "${line.text}"`
    ).join('\n');

    const rawComplianceText = JSON.stringify(complianceReport);

    const mitigatorPrompt = `
      You are the Risk Operations Specialist and Creative Producer for "Boomer & Kev Studio".
      Your job is to read the strict legal warnings generated by the Attorney Agent (defamation, copyright, right of publicity, LGPD, EU AI Act) and find the creative "loopholes" and "fine print" (entrelinhas) to allow us to post the videos anyway while fully protecting the studio from strikes, demonetization, or lawsuits.

      YOUR OBJECTIVE:
      Do not say "cancel the video." Find the workarounds! Bleep words, suggest visual cover-ups, use phonetic parody names (e.g. changing 'Sportsbet' to 'SposBet' or 'OzBet'), or rewrite lines surgically so the humor and viral impact are retained but the legal liability drops to zero.

      LAWYER SCAN REPORT:
      """
      ${rawComplianceText}
      """

      ORIGINAL SCRIPT:
      """
      ${scriptText}
      """

      Return a JSON object containing:
      - platformStrikeRisk: {
          tiktok: number (0-100 scale),
          youtube: number (0-100 scale),
          instagram: number (0-100 scale)
        }
      - loopholeStrategy: A detailed explanation of the creative "entrelinhas" strategy to bypass the legal restrictions.
      - requiredProductionTricks: An array of specific production hacks (e.g. "Add a visual pixelation blur over the character's hands at Scene 3", "Insert audio beep over the word 'Sportsbet'").
      - modifiedScript: An array of the script lines updated with your surgical, safe-parody rewrites. Each modified script line must have:
        - id: string (matching original)
        - characterId: string
        - text: the updated, legally safe but funny dialogue text.
        - shotType: string
        - action: string
        - durationEst: number
        - emotion: string
    `;

    const { response } = await fetchWithRetry(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: mitigatorPrompt }] }]
      })
    });

    const data = await response.json();

    if (data.error) {
      throw new Error(data.error.message || 'Gemini API Risk Mitigation Agent Error');
    }

    const content = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!content) {
      throw new Error('No mitigation analysis returned from Gemini');
    }

    let jsonStr = content.trim();
    const jsonMatch = content.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      jsonStr = jsonMatch[0];
    }

    const parsedMitigation = JSON.parse(jsonStr);
    return NextResponse.json(parsedMitigation);

  } catch (error) {
    console.error('RISK_MITIGATION_AGENT_FAIL:', error);
    const message = error instanceof Error ? error.message : 'Unknown risk mitigation agent error';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
